agent:
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
  added_encode_modal:
    encode_modal:
      - "task"
      # - "state"
    num_tasks: 50
    num_actions: 9
    num_states: 7
    action_dim: 400
    task_dim: 400
    state_dim: 400
  data_aug: true
  depth: false
  dino: false
  only_act: true

pretrain:
  path: ??? # Specify path to snapshot.pt to load pretrained encoder and decoder
  just_encoder_decoders: true
